### ISSUE TITLE
Tootlip legend stacking order diffferent from graph

### ISSUE THREAD

**Issue by surdu** [code4romania/covid-19-date-la-zi#389]
In the tooltip for the graph, the order of the legend is different from the order on the stacked graph:

<img width="280" alt="Screen Shot 2020-10-26 at 10 26 39 AM" src="https://user-images.githubusercontent.com/11520795/97149802-e9705e00-1775-11eb-9bd2-b7cdce831d0d.png">

"Confirmati, Vindecati, Decedati"  vs "Decedati, Vindecati, Confirmati"

This makes it harder than it should to see the data at a glance.

**Comment by bertearazvan** [comment]
@catileptic I found a way around this issue by using the `tooltip.formatter` (here)[https://echarts.apache.org/en/option.html#tooltip.formatter]. Hope I didn't come too late to the party :D 

![stacking](https://user-images.githubusercontent.com/30385700/104489223-aaf97b00-55cf-11eb-9169-e20b42e7ce4b.png)

Is there any chance I could have access to create a PR? I get 403 now.
Moreover, it would be my pleasure to contribute to other projects in my free time from now on. 

Multumesc :)

**Comment by catileptic** [comment]
@bertearazvan you can create a PR by first forking this repo, committing the changes to your fork, to a branch (it will make it easier to stay in sync with the upstream branches if you always work on a feature branch) and then create a PR that aims to merge your branch into the upstream `develop` branch. 

Thank you for offering a solution and especially for the enthusiasm of contributing some more! It's something we always, always appreciate. 

Could I extend an invitation to you, to join our Slack? I'd need your email address, for that.

**Comment by bertearazvan** [comment]
@catileptic Awesome and exciting, looking forward to how this will unveil. 
I will send you a pm on some other platform to not make my email public. 
Thank you very much for the suggestion on how to contribute, will do exactly that.
