### ISSUE TITLE
Day-of-week in graph tooltips

### ISSUE THREAD

**Issue by dapetcu21** [code4romania/covid-19-date-la-zi#410]
I noticed there's a certain recurrent weekly envelope over the number-of-new-cases graph (for example, mondays are consistenly the lowest in new discovered cases all week).

Therefore it would be useful to be able to compare the numbers from one day with the numbers from the same day 1,2,3,etc weeks ago.

My suggestion for an easy fix for this would be to add the day of the week in the tooltip (for example, this could say "luni, 14 decembrie" instead of "14 decembrie"):

<img width="956" alt="Screen Shot 2021-01-28 at 14 29 43" src="https://user-images.githubusercontent.com/428060/106138802-457fbf80-6175-11eb-99f7-77daca00bcf9.png">

**Comment by popsorina** [comment]
I will take this.
