### ISSUE TITLE
Total cases by county returns "undefined" due to wrong JSON file format

### ISSUE THREAD

**Issue by horatiuvlad** [code4romania/covid-19-date-la-zi#424]
Hovering over the incidence map returns `undefined` for the label called `Cazuri totale`:

![image](https://user-images.githubusercontent.com/9079544/111903356-96f84c80-8a4a-11eb-953c-edca701a2ca8.png)

This is due to the fact that today's (21st of March, 2021) `latestData.json` file returns an invalid data format for `currentDayStats.countyInfectionsNumbers` - it returns the same keys specific for `currentDayStats.distributionByAge`, although the numbers slightly differ:
```
  "currentDayStats": {
    ...
    "distributionByAge": {
      "0-9": 19316,
      "10-19": 36927,
      "20-29": 89464,
      "30-39": 153524,
      "40-49": 180974,
      "50-59": 164635,
      "60-69": 128284,
      "70-79": 78447,
      ">80": 41139,
      "în procesare": 138
    },
    "countyInfectionsNumbers": {
      "0-9": 19479,
      "10-19": 37143,
      "20-29": 89840,
      "30-39": 154170,
      "40-49": 181745,
      "50-59": 165322,
      "60-69": 128994,
      "70-79": 78938,
      ">80": 41347,
      "în procesare": 137
    },
    ...
```

Here's a snapshot of `https://d35p9e4fm9h3wo.cloudfront.net/latestData.json` as of 21st of March, 2021 (~13pm):
https://pastebin.com/raw/v2K7bXsN

The parser script assumes that `countyInfectionsNumbers`'s keys are the county names instead of age groups, so that's where the `undefined` propagates from:
https://github.com/code4romania/covid-19-date-la-zi/blob/develop/utils/parse.js#L56

And this is where the `undefined` is being rendered, as effect of the parser:
https://github.com/code4romania/covid-19-date-la-zi/blob/develop/components/cards/counties-map/counties-map.jsx#L20

I am unaware of the degree of control you have over your input data, so I'm unable to propose a fix for this matter. Just wanted to let you know of the problem. Hope it helps!

Also I have to say I am deeply grateful for everything you guys are doing. I think you are a group of heroes and I truly believe your work will have a substantial impact over Romania (or even abroad), giving enough time. Keep it up and keep kicking ass!

**Comment by catileptic** [comment]
Thank you for reporting this issue and thank you for your kind words!

We have fixed the issue. The data set is correct now, `countyInfectionsNumbers` is populated with what you'd expect. The changes will take a few minutes to propagate on the frontend due to caching.
