### ISSUE TITLE
Add a11y tables for all graphs

### ISSUE THREAD

**Issue by catileptic** [code4romania/covid-19-date-la-zi#425]
Every graph needs to have the data available in tabular format, following the example of the [Cases per day card](https://github.com/code4romania/covid-19-date-la-zi/blob/develop/components/cards/cases-per-day-card/cases-per-day-card.jsx#L175). 

Add such tables for:
* Doze de vaccin administrate pe zile (Vaccines per day)
* Cazuri per categorie de vârstă, în timp (Age category)
* Cazuri după vârstă (Age)

**Comment by Utwo** [comment]
We already have the tables but we don't know how to properly display them only for screen readers. Hiding them with .sw-only css class will add a long scroll bar on chrome. https://github.com/code4romania/covid-19-date-la-zi/pull/423

Anyone is more then welcome to look into this problem.

**Comment by swoopstyle** [comment]
I offer tribute!

**Comment by Utwo** [comment]
Sure, let me know if we can help you with the project setup or any other questions ;)

**Comment by catileptic** [comment]
This Issue still needs tables for the other remaining graphs :)

**Comment by GabrielMajeri** [comment]
@catileptic I want to work on this!
