### ISSUE TITLE
Abnormal spike in county cases 2021.12.18

### ISSUE THREAD

**Issue by jeffpires** [code4romania/covid-19-date-la-zi#461]
In **latestData.json**, *countyInfectionsNumbers* shows an unusually large increase on 2021.12.18 for many county-level case totals when compared to the surrounding dates.  For instance, Ilfov:

![image](https://user-images.githubusercontent.com/5229803/149507516-c3c78c7c-30c3-4d8a-9e3d-a675b23986a2.png)

This jump is not consistent with national-level case totals in the same date range.  Might it be possible to correct the dates of these cases for county-level data in mid-December 2021?  Many thanks!

**Comment by catileptic** [comment]
The numbers published in [Date la zi](https://datelazi.ro/) come straight from news bulletins that the official authorities that communicate on the subject of the pandemic in Romania put out. [This](https://stirioficiale.ro/informatii/buletin-de-presa-18-decembrie-2021-ora-13-00) is the bulletin for December 18th 2021. The number of cases is taken from the table that starts right beneath this phrase: "Distribuția pe județe a cazurilor per total și a celor noi o regăsiți în tabelul de mai jos.". 

For example, for Ilfov, on that day:
```
The total number of confirmed cases: 76.719
The number of new cases: 1085
Incidence: 0,88
```

I am closing this. Feel free to re-open the Issue if you would like to pursue this conversation further. :)
