### ISSUE TITLE
historicalData countryInfectionsNumbers data errors

### ISSUE THREAD

**Issue by jeffpires** [code4romania/covid-19-date-la-zi#468]
The historical data in latestData.json appears to be experiencing some recent data errors:

1) the most recent date in the dataset, 2022-02-22, seems to reflect numbers which should belong to 2022-**01**-22.  Records for the date 2022-01-22 are now missing.  For example, Bucharest:
![image](https://user-images.githubusercontent.com/5229803/155518741-0cdfe8bb-6292-4fa5-9e65-7d2b5607b8c0.png)

2) Values for Sibiu, Harghita, Cluj, and Botosani on 2022-02-17 are suspicious outliers, as they don't align well with their surrounding dates.

**Comment by idormenco** [comment]
@jeffpires thanks for spotting this issue , we will fix this ASAP. @decembrya will investigate

**Comment by decembrya** [comment]
Hi @jeffpires, thank you for reporting this and apologies it's taking so long for us to get to it. 
It's been a crazy week.

I've fixed the data for 2022-02-17, still waiting for some data to come in  to re-add 2022-01-22 and will notify when that is done.

**Comment by decembrya** [comment]
I've just uploaded the data for 2022-01-22. 
Do let us know if you find any other problems with the data, we'll be happy to fix.

Will be closing this issue.
